# Generated by Django 3.0.8 on 2020-07-03 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banks',
            name='ifsc',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
    ]
